<script setup>
import { ref } from 'vue'

defineProps({
  msg: String
})

const count = ref(0)
const selectedCity = null
const			cities = [
				{name: 'London', code: 'LND'},
				{name: 'Paris', code: 'PRS'},
				{name: 'Rome', code: 'RM'}
			]
</script>

<template>
  
  
</template>

<style scoped>
a {
  color: #42b983;
}

</style>

SQL> CREATE TABLE is02.students(
student_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
first_name VARCHAR2(50) NOT NULL,
last_name VARCHAR2(50) NOT NULL,
PRIMARY KEY(student_id));

Table created.

SQL> CREATE TABLE is02.teacher(
teacher_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
first_name VARCHAR2(50) NOT NULL,
last_name VARCHAR2(50) NOT NULL,
salary NUMBER NOT NULL,
PRIMARY KEY(teacher_id));

Table created.

SQL> CREATE TABLE is02.major(
major_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
major_name VARCHAR2(50) NOT NULL,
PRIMARY KEY(major_id));

Table created.

