<template lang="">
  <AdminBlankPage>
    <template v-slot:header>
      <div class="header-wrapper">
        <div class="header-wrapper__left">Tạo đơn hàng</div>
        <div class="header-wrapper__right">
          <Button label="Thoát" class="p-button-outlined p-button-danger" />
          <Button
            type="button"
            label="Thêm đơn hàng"
            icon="pi pi-plus"
            class="p-button-info ml-2"
            badgeClass="p-badge-danger"
          />
        </div>
      </div>
    </template>
    <template v-slot:main>
      <div class="main-wrapper">
        <Card>
          <template #title>Doanh số</template>
          <template #content>
            <div class="">
              <LineChartVue></LineChartVue>
              <LineChartVue></LineChartVue>
            </div>
          </template>
        </Card>
      </div>
    </template>
  </AdminBlankPage>
</template>
<script>
import AdminBlankPage from "../AdminBlankPage.vue";
import LineChartVue from "./components/LineChart.vue";
export default {
  components: {
    AdminBlankPage,
    LineChartVue,
  },
  data() {
    return {};
  },
};
</script>
<style lang="scss" scoped>
.header-wrapper {
  width: 100%;
  display: flex;
  justify-content: space-between;
  align-items: center;

  &__left {
  }

  &__right {
  }
}
</style>
<!-- 
SQL> CREATE TABLE is01.persons(
person_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
first_name VARCHAR2(50) NOT NULL,
last_name VARCHAR2(50) NOT NULL,
PRIMARY KEY(person_id)
);

Table created.

SQL> CREATE TABLE is01.job(
job_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
job_name VARCHAR2(50) NOT NULL,
salary NUMBER NOT NULL,
PRIMARY KEY(job_id)
);

Table created.

SQL> CREATE TABLE is01.major(
major_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
major_name VARCHAR2(50) NOT NULL,
PRIMARY KEY(major_id)
);

Table created.

SQL> CREATE TABLE is02.students(
student_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
first_name VARCHAR2(50) NOT NULL,
last_name VARCHAR2(50) NOT NULL,
PRIMARY KEY(student_id));

Table created.

SQL> CREATE TABLE is02.teacher(
  2  teacher_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  3  first_name VARCHAR2(50) NOT NULL,
  4  last_name VARCHAR2(50) NOT NULL,
  5    4      salary NUMBER NOT NULL,
  6  PRIMARY KEY(teacher_id));
  4      salary NUMBER NOT NULL,
  *
ERROR at line 5:
ORA-00904: : invalid identifier


SQL> CREATE TABLE is02.teacher(
teacher_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  first_name VARCHAR2(50) NOT NULL,last_name VARCHAR2(50) NOT NULL,salary NUMBER NOT NULL)

  SQL> CREATE TABLE is02.teacher(
  teacher_id NUMBER GENERATED BY DEFAULT AS IDENTITY,first_name VARCHAR2(50) NOT NULL,last_name VARCHAR2(50) NOT NULL,salary NUMBER NOT NULL,PRIMARY KEY(teacher_id));

Table created.

SQL> CREATE TABLE is02.major(
major_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
major_name VARCHAR2(50) NOT NULL,
PRIMARY KEY(major_id));

Table created.

SQL> INSERT INTO is01.persons(first_name,last_name) VALUES ('huy','trinnh');
INSERT INTO is01.persons(first_name,last_name) VALUES ('huy','trinnh')
                 *
ERROR at line 1:
ORA-01950: no privileges on tablespace 'USERS'


SQL> connect is01
Enter password:
ERROR:
ORA-01045: user IS01 lacks CREATE SESSION privilege; logon denied


Warning: You are no longer connected to ORACLE.
SQL> alter session set "_ORACLE_SCRIPT"=true;
SP2-0640: Not connected
SQL> -->